### ISSUE TITLE
"create_l2_port_channel": action failed

### ISSUE THREAD

**Issue by mab27** [StackStorm-Exchange/stackstorm-network_essentials#4]
When trying the action, I got an error message stating this: AttributeError: 'CreatePortChannel' object has no attribute 'pmgr'.

Other actions from the pack works fine on the same device.

mab@mab-infra:/opt/stackstorm/packs/default/actions$ st2 run network_essentials.create_l2_port_channel mgmt_ip=172.29.104.101 intf_type=tengigabitethernet ports="1/0/10,1/0/11,1/0/12" port_channel_id=15
.
id: 58dbbf467cae2208ba98756e
status: failed
parameters: 
  intf_type: tengigabitethernet
  mgmt_ip: 172.29.104.101
  port_channel_id: '15'
  ports:
  - 1/0/10
  - 1/0/11
  - 1/0/12
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/network_essentials/actions/create_l2_port_channel.py", line 38, in run
    with self.pmgr(conn=self.conn, auth=self.auth) as device:
AttributeError: 'CreatePortChannel' object has no attribute 'pmgr'
"
  stdout: ''

**Comment by samirsss** [comment]
We'll verify this and take a quick look today. I think this issue is fixed but hasnt been pushed onto the exchange.

**Comment by samirsss** [comment]
Verified that this issue is fixed in the latest version of the pack
